import FeatureProjects from '@/components/FeatureProjects'
import FeatureProjects2 from '@/components/FeatureProjects2'
import Hero from '@/components/Hero'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>DevTeams</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <FeatureProjects2 />
      {/* <FeatureProjects /> */}
    </>
  )
}
